name: Pipeline CI - Lab Ingenieria de Software II

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pruebas:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test
